In [1]:
## Importando o que for necessário
import pandas as pd
import numpy as np
from zipfile import ZipFile
import pathlib

In [ ]:
## Montando o Google Drive
# from google.colab import drive
# drive.mount('/content/drive')

# Um mês

In [ ]:
## Lendo os arquivos
# Determinando o Caminho
# sCaminho = '/content/drive/MyDrive/Projetos/IDP/MBA/SetorPublicoI/PNADCOVID/'
sCaminho = f"{pathlib.Path().absolute()}/"

In [ ]:
## Lendo os arquivos zipados
sArquivo = f"{sCaminho}PNAD_COVID_112020.zip"
with ZipFile(sArquivo) as z:
    PNAD_COVID_112020 = pd.read_csv(z.open("PNAD_COVID_112020.csv"))
    print("Feito!")

PNAD_COVID_112020.csv

In [ ]:
## Vendo as 5 primeiras linhas
PNAD_COVID_112020.head()

,Ano,UF,CAPITAL,RM_RIDE,V1008,V1012,V1013,V1016,Estrato,UPA,...,F001,F0021,F0022,F002A1,F002A2,F002A3,F002A4,F002A5,F0061,F006
0,2020,11,11.0,NaN,1,4,11,7,1110011,110015970,...,1,NaN,NaN,1,1,1,2,1,1,1.0
1,2020,11,11.0,NaN,1,4,11,7,1110011,110015970,...,1,NaN,NaN,1,1,1,2,1,1,1.0
2,2020,11,11.0,NaN,1,4,11,7,1110011,110015970,...,1,NaN,NaN,1,1,1,2,1,1,1.0
3,2020,11,11.0,NaN,1,4,11,7,1110011,110015970,...,1,NaN,NaN,1,1,1,2,1,1,1.0
4,2020,11,11.0,NaN,2,1,11,7,1110011,110015970,...,1,NaN,NaN,1,1,1,2,1,1,1.0

In [ ]:
# Vendo o tamanho da base
print(f"Linhas: {PNAD_COVID_112020.shape[0]}; Colunas: {PNAD_COVID_112020.shape[1]}")

Linhas: 381438; Colunas: 148

In [ ]:
## Filtrando algumas colunas (de informações de saúde, empréstimos e característica da habitação)
# -> Torna o DataFrame mais leve!
for letra in ["B", "E", "F"]:
    PNAD_COVID_112020 = PNAD_COVID_112020.loc[:, ~PNAD_COVID_112020.columns.str.startswith(letra)]

# Vendo o tamanho da base
print(f"Linhas: {PNAD_COVID_112020.shape[0]}; Colunas: {PNAD_COVID_112020.shape[1]}")

Linhas: 381438; Colunas: 88

In [ ]:
## Descrevendo cada coluna: outras estatísticas!
PNAD_COVID_112020.describe()

,Ano,UF,CAPITAL,RM_RIDE,V1008,V1012,V1013,V1016,UPA,V1022,...,D0031,D0033,D0041,D0043,D0051,D0053,D0061,D0063,D0071,D0073
count,381438.0,381438.000000,90745.000000,121419.000000,381438.000000,381438.000000,381438.0,381438.0,3.814380e+05,381438.000000,...,381438.000000,36732.000000,381438.000000,13793.000000,381438.000000,184767.000000,381438.000000,5206.000000,381438.000000,18972.000000
mean,2020.0,31.609470,30.921395,31.437922,7.477763,2.499164,11.0,7.0,3.161946e+08,1.236712,...,1.903701,196.776870,1.963839,1118.728703,1.515604,574.792079,1.986352,1295.144065,1.950262,1500.951191
std,0.0,10.876455,13.037352,9.530824,4.030199,1.115526,0.0,0.0,1.087809e+08,0.425065,...,0.295001,105.635882,0.186690,291.835315,0.499757,425.715959,0.116026,471.093944,0.217404,2307.957896
min,2020.0,11.000000,11.000000,13.000000,1.000000,1.000000,11.0,7.0,1.100000e+08,1.000000,...,1.000000,41.000000,1.000000,1045.000000,1.000000,262.000000,1.000000,1045.000000,1.000000,1.000000
25%,2020.0,24.000000,22.000000,26.000000,4.000000,2.000000,11.0,7.0,2.400171e+08,1.000000,...,2.000000,130.000000,2.000000,1045.000000,1.000000,300.000000,2.000000,1045.000000,2.000000,500.000000
50%,2020.0,31.000000,31.000000,32.000000,7.000000,2.000000,11.0,7.0,3.103009e+08,1.000000,...,2.000000,171.000000,2.000000,1045.000000,2.000000,600.000000,2.000000,1080.000000,2.000000,890.000000
75%,2020.0,41.000000,41.000000,35.000000,11.000000,3.000000,11.0,7.0,4.100935e+08,1.000000,...,2.000000,250.000000,2.000000,1045.000000,2.000000,600.000000,2.000000,1435.000000,2.000000,1500.000000
max,2020.0,53.000000,53.000000,52.000000,14.000000,4.000000,11.0,7.0,5.300511e+08,2.000000,...,2.000000,890.000000,2.000000,5200.000000,2.000000,8400.000000,2.000000,8500.000000,2.000000,32000.000000

In [ ]:
## Contando número de NAs por colunas
PNAD_COVID_112020.isna().sum()

Ano             0
UF              0
CAPITAL    290693
RM_RIDE    260019
V1008           0
            ...
D0053      196671
D0061           0
D0063      376232
D0071           0
D0073      362466
Length: 88, dtype: int64

In [ ]:
## Contando os motivos elencados pelos alunos para não realizarem atividades escolares
## disponibilizadas na semana passada
# NA: fez a atividade ou estava de férias
# Padrão: dropna=True
PNAD_COVID_112020.A007A.value_counts(dropna=False)

NaN    380190
2.0       373
6.0       265
1.0       262
5.0       261
4.0        52
3.0        35
Name: A007A, dtype: int64

In [ ]:
## Contando apenas as pessoas que responderam
# Por padrão, a contagem é feita de forma decrescente; podemos ver de forma crescente...
PNAD_COVID_112020["A007A"].value_counts(dropna=True, ascending=True)

3.0     35
4.0     52
5.0    261
1.0    262
6.0    265
2.0    373
Name: A007A, dtype: int64

In [ ]:
#... e selecionar apenas as linhas que não fizeram atividades por problemas de saúde própria (A007A == 3)
PNAD_COVID_112020.loc[PNAD_COVID_112020["A007A"] == 3]

,Ano,UF,CAPITAL,RM_RIDE,V1008,V1012,V1013,V1016,UPA,V1022,...,D0031,D0033,D0041,D0043,D0051,D0053,D0061,D0063,D0071,D0073
36318,2020,15,NaN,NaN,8,1,11,7,150032300,1,...,2,NaN,2,NaN,1,600.0,2,NaN,2,NaN
46399,2020,17,NaN,NaN,10,2,11,7,170030463,1,...,2,NaN,2,NaN,2,NaN,2,NaN,2,NaN
51524,2020,21,NaN,NaN,7,1,11,7,210023860,1,...,2,NaN,1,1045.0,1,600.0,2,NaN,2,NaN
54134,2020,21,NaN,NaN,8,1,11,7,210064903,2,...,2,NaN,2,NaN,1,900.0,1,1045.0,2,NaN
68436,2020,22,22.0,22.0,1,3,11,7,220032884,1,...,2,NaN,1,1045.0,2,NaN,2,NaN,2,NaN
69582,2020,22,22.0,22.0,2,3,11,7,220001634,1,...,2,NaN,2,NaN,1,600.0,2,NaN,2,NaN
73049,2020,22,NaN,NaN,3,3,11,7,220037321,2,...,1,130.0,2,NaN,1,600.0,2,NaN,2,NaN
74290,2020,22,NaN,NaN,4,3,11,7,220047089,2,...,2,NaN,2,NaN,1,300.0,2,NaN,2,NaN
90603,2020,23,NaN,NaN,5,1,11,7,230004499,2,...,2,NaN,2,NaN,1,330.0,2,NaN,2,NaN
98667,2020,24,NaN,NaN,9,3,11,7,240042177,1,...,2,NaN,2,NaN,1,600.0,2,NaN,2,NaN
105324,2020,25,NaN,NaN,7,3,11,7,250039430,2,...,1,78.0,2,NaN,1,1200.0,2,NaN,2,NaN
119627,2020,26,NaN,NaN,2,1,11,7,260041418,2,...,2,NaN,2,NaN,1,600.0,2,NaN,2,NaN
119985,2020,26,NaN,NaN,9,4,11,7,260095873,2,...,2,NaN,2,NaN,1,300.0,2,NaN,2,NaN
129026,2020,27,27.0,27.0,4,1,11,7,270010985,1,...,1,130.0,2,NaN,2,NaN,2,NaN,2,NaN
135183,2020,27,NaN,NaN,8,1,11,7,270049062,1,...,2,NaN,1,1045.0,1,600.0,2,NaN,2,NaN
136286,2020,27,NaN,NaN,12,3,11,7,270047986,1,...,1,170.0,2,NaN,1,600.0,2,NaN,2,NaN
141129,2020,28,NaN,28.0,4,4,11,7,280021806,1,...,2,NaN,2,NaN,1,300.0,2,NaN,2,NaN
141130,2020,28,NaN,28.0,4,4,11,7,280021806,1,...,2,NaN,2,NaN,1,300.0,2,NaN,2,NaN
143693,2020,28,NaN,NaN,1,2,11,7,280004644,1,...,2,NaN,1,1045.0,1,600.0,2,NaN,2,NaN
163012,2020,29,NaN,NaN,7,4,11,7,290245874,2,...,1,244.0,2,NaN,1,323.0,2,NaN,2,NaN
166539,2020,31,31.0,31.0,1,2,11,7,310310160,1,...,2,NaN,2,NaN,1,300.0,2,NaN,2,NaN
166555,2020,31,31.0,31.0,7,2,11,7,310310160,1,...,2,NaN,1,1045.0,1,300.0,2,NaN,2,NaN
166556,2020,31,31.0,31.0,7,2,11,7,310310160,1,...,2,NaN,1,1045.0,1,300.0,2,NaN,2,NaN
188984,2020,31,NaN,NaN,2,4,11,7,310307290,2,...,1,380.0,2,NaN,1,600.0,2,NaN,2,NaN
188985,2020,31,NaN,NaN,2,4,11,7,310307290,2,...,1,380.0,2,NaN,1,600.0,2,NaN,2,NaN
206104,2020,32,NaN,NaN,3,4,11,7,320055396,1,...,2,NaN,2,NaN,2,NaN,2,NaN,2,NaN
212123,2020,32,NaN,NaN,9,3,11,7,320025801,1,...,2,NaN,1,1045.0,1,600.0,2,NaN,2,NaN
212491,2020,32,NaN,NaN,10,1,11,7,320031838,1,...,2,NaN,2,NaN,2,NaN,2,NaN,2,NaN
220579,2020,33,33.0,33.0,5,3,11,7,330180323,1,...,2,NaN,1,1098.0,1,600.0,2,NaN,2,NaN
226777,2020,33,NaN,33.0,3,3,11,7,330149495,1,...,2,NaN,2,NaN,2,NaN,2,NaN,2,NaN
265253,2020,35,NaN,NaN,6,2,11,7,350544709,2,...,2,NaN,2,NaN,1,300.0,2,NaN,2,NaN
270017,2020,35,NaN,NaN,11,1,11,7,350582040,1,...,1,258.0,2,NaN,1,300.0,2,NaN,2,NaN
298542,2020,42,NaN,NaN,5,4,11,7,420013740,1,...,2,NaN,2,NaN,2,NaN,2,NaN,2,NaN
324968,2020,43,NaN,43.0,7,4,11,7,430160102,1,...,2,NaN,2,NaN,2,NaN,2,NaN,2,NaN
342529,2020,50,50.0,NaN,6,4,11,7,500032230,1,...,2,NaN,1,3135.0,2,NaN,2,NaN,2,NaN

## Alternativa (mais abrangente) ao value_counts: groupby

In [ ]:
## Contando o número de homens e mulheres
# Mudando o rótulo das colunas
PNAD_COVID_112020['Sexo'] = PNAD_COVID_112020['A003'].apply(lambda i: "Homem" if i == 1 else "Mulher")

# Contando usando value_counts
PNAD_COVID_112020.Sexo.value_counts(dropna=False)

Mulher    198827
Homem     182611
Name: Sexo, dtype: int64

In [ ]:
## Contando usando groupby
# Apenas valores da própria coluna
PNAD_COVID_112020.groupby("Sexo")["Sexo"].count()

Sexo
Homem     182611
Mulher    198827
Name: Sexo, dtype: int64

In [ ]:
# Todas as colunas
PNAD_COVID_112020.groupby("Sexo").count()

,Ano,UF,CAPITAL,RM_RIDE,V1008,V1012,V1013,V1016,UPA,V1022,...,D0031,D0033,D0041,D0043,D0051,D0053,D0061,D0063,D0071,D0073
Sexo,,,,,,,,,,,,,,,,,,,,,
Homem,182611,182611,42016,56521,182611,182611,182611,182611,182611,182611,...,182611,17211,182611,6574,182611,89201,182611,2528,182611,9062
Mulher,198827,198827,48729,64898,198827,198827,198827,198827,198827,198827,...,198827,19521,198827,7219,198827,95566,198827,2678,198827,9910

In [ ]:
## Usando value_counts para obter valores percentuais
PNAD_COVID_112020.Sexo.value_counts(normalize=True, dropna=True)

Mulher    0.521256
Homem     0.478744
Name: Sexo, dtype: float64

### E os pesos da PNAD?

In [ ]:
## Vendo os pesos
PNAD_COVID_112020[["Ano", "V1032"]]

In [ ]:
## Temos que usar groupby!
# Contando em termos absolutos
PNAD_COVID_112020.groupby("Sexo")["V1032"].sum() / 1000000

Sexo
Homem     1.034634e+08
Mulher    1.081890e+08
Name: V1032, dtype: float64

In [ ]:
# Termos percentuais
contagem_sexo = PNAD_COVID_112020.groupby("Sexo")["V1032"].sum()
percentual_sexo = contagem_sexo / PNAD_COVID_112020["V1032"].sum()
percentual_sexo

Sexo
Homem     0.488837
Mulher    0.511163
Name: V1032, dtype: float64

In [ ]:
## Vendo gênero por estado
# Sem pesos
PNAD_COVID_112020.groupby(["UF", "Sexo"])["Sexo"].count().unstack()

Sexo  Homem  Mulher
UF
11     2942    3059
12     2937    3165
13     5076    5265
14     2776    2838
15     5750    6128
16     1184    1288
17     2525    2562
21     9812   10592
22     4037    4443
23     7691    8491
24     3657    4118
25     4640    5233
26     8090    9048
27     5411    5992
28     3785    4228
29     8095    8968
31    16648   17691
32     7627    8236
33    13417   15648
35    15283   16821
41     9613   10259
42    11257   12175
43    10552   11379
50     4187    4470
51     5615    5744
52     6823    7372
53     3181    3614

In [ ]:
# Com pesos
contagem_sexo_uf = PNAD_COVID_112020.groupby(["UF", "Sexo"])["V1032"].sum()
pesos_uf = PNAD_COVID_112020.groupby("UF")["V1032"].sum()
percentual_sexo_uf = (contagem_sexo_uf / pesos_uf).unstack()
percentual_sexo_uf

Sexo     Homem    Mulher
UF
11    0.505392  0.494608
12    0.500026  0.499974
13    0.501890  0.498110
14    0.517738  0.482262
15    0.501164  0.498836
16    0.500688  0.499312
17    0.503213  0.496787
21    0.491300  0.508700
22    0.484030  0.515970
23    0.484975  0.515025
24    0.487399  0.512601
25    0.482430  0.517570
26    0.479991  0.520009
27    0.479147  0.520853
28    0.482511  0.517489
29    0.485675  0.514325
31    0.492328  0.507672
32    0.492251  0.507749
33    0.478354  0.521646
35    0.487666  0.512334
41    0.489761  0.510239
42    0.496108  0.503892
43    0.486587  0.513413
50    0.496049  0.503951
51    0.506632  0.493368
52    0.495704  0.504296
53    0.480551  0.519449

### Urbano x Rural (V1022)

In [ ]:
## Remapeando
PNAD_COVID_112020['Rural'] = PNAD_COVID_112020['V1022'].apply(lambda i: "Urbano" if i == 1 else "Rural")

In [ ]:
## Análise sem pesos
# Absoluta
PNAD_COVID_112020["Rural"].value_counts(dropna=True)

Urbano    291147
Rural      90291
Name: Rural, dtype: int64

In [ ]:
# Relativa
PNAD_COVID_112020["Rural"].value_counts(dropna=True, normalize=True)

Urbano    0.763288
Rural     0.236712
Name: Rural, dtype: float64

In [ ]:
## Com pesos
# Absoluta
PNAD_COVID_112020.groupby("Rural")["V1032"].sum() / 1000000

Rural
Rural     3.027627e+07
Urbano    1.813761e+08
Name: V1032, dtype: float64

In [ ]:
# Relativa: diferença de quase 10% quando não se consideram os pesos!
PNAD_COVID_112020.groupby("Rural")["V1032"].sum() / PNAD_COVID_112020["V1032"].sum()

Rural
Rural     0.143047
Urbano    0.856953
Name: V1032, dtype: float64

## Médias de Educação

In [ ]:
## Remapeando
Valores_PNAD = ["SI", "Fund Inc", "Fund Comp", "Méd Inc", "Med Comp", "Sup Inc", "Sup Comp", "Pós"]
PNAD_COVID_112020["Educação"] = PNAD_COVID_112020["A005"].replace([1, 2, 3, 4, 5, 6, 7, 8], Valores_PNAD)

In [ ]:
## Contando por escolaridade
np.around(PNAD_COVID_112020['Educação'].value_counts(normalize=True, dropna=True)*100, 2)

Fund Inc     33.69
Med Comp     22.32
SI           10.77
Méd Inc       9.38
Sup Comp      9.37
Fund Comp     6.63
Sup Inc       5.19
Pós           2.65
Name: Educação, dtype: float64

In [ ]:
## Gênero e Educação
# Sem pesos e relativo (frente ao total do gênero)
contagem_sexo_educ = PNAD_COVID_112020.groupby(["Sexo", "Educação"])["Educação"].count()
total_sexo = PNAD_COVID_112020.groupby("Sexo")["Sexo"].count()
(contagem_sexo_educ / total_sexo).unstack()

Educação,Fund Comp,Fund Inc,Med Comp,Méd Inc,Pós,SI,Sup Comp,Sup Inc
Sexo,,,,,,,,
Homem,0.066573,0.355942,0.216444,0.100054,0.020404,0.112907,0.077580,0.050096
Mulher,0.065977,0.319464,0.229405,0.088077,0.032063,0.102969,0.108532,0.053514

In [ ]:
# Sem pesos e relativo (frente ao total do grau de educação)
contagem_educ_sexo = PNAD_COVID_112020.groupby(["Educação", "Sexo"])["Educação"].count()
total_educ = PNAD_COVID_112020.groupby("Educação")["Educação"].count()
(contagem_educ_sexo / total_educ).unstack()

Sexo          Homem    Mulher
Educação
Fund Comp  0.480989  0.519011
Fund Inc   0.505762  0.494238
Med Comp   0.464252  0.535748
Méd Inc    0.510606  0.489394
Pós        0.368874  0.631126
SI         0.501764  0.498236
Sup Comp   0.396324  0.603676
Sup Inc    0.462300  0.537700

# Múltiplos meses!

In [2]:
## Lendo todos os dados de maio a novembro
sCaminho = f"{pathlib.Path().absolute()}/"

# Lista contendo todos os DataFrames
frames = []
for i in range(5, 12):
  mes = str(i).zfill(2)  # colocando 0, caso precise
  with ZipFile(sCaminho + 'PNAD_COVID_'+mes+'2020.zip') as z:
    with z.open('PNAD_COVID_'+mes+'2020.csv') as f:
      frames.append(pd.read_csv(f))

## Criando um DataFrame com todos os dados
PNAD_COVID = pd.concat(frames)

## Filtrando algumas colunas (de informações de saúde, empréstimos e característica da habitação)
# -> Torna o DataFrame mais leve!
for letra in ["B", "E", "F"]:
    PNAD_COVID = PNAD_COVID.loc[:, ~PNAD_COVID.columns.str.startswith(letra)]

# Vendo o tamanho da base
print(f"Linhas: {PNAD_COVID.shape[0]}; Colunas: {PNAD_COVID.shape[1]}")

Linhas: 2650459; Colunas: 88

In [3]:
## Vendo observações por mês
PNAD_COVID.groupby('V1013').size()

V1013
5     349306
6     381270
7     384166
8     386520
9     387298
10    380461
11    381438
dtype: int64

In [4]:
## Tamanho total da base
print(f"Linhas: {PNAD_COVID.shape[0]}; Colunas: {PNAD_COVID.shape[1]}")

Linhas: 2650459; Colunas: 88

## Taxa de Desocupação

A **taxa de desocupação** é calculada em relação à **força de trabalho**, ou seja, pessoas que trabalham ou estão procurando emprego.

A **taxa de participação** é calculada como a força de trabalho frente à população total.

O **nível de ocupação** é calculaod como a razão da população ocupada frente à total.

In [5]:
## Queremos determinar se uma pessoa é ocupada/desocupada e já imputar o seu peso
# Como o peso é uma coluna, não podemos usar lambda functions 
## Ocupado
PNAD_COVID["Ocupado"] = PNAD_COVID["C007"].apply(lambda i: 1 if i <= 8 else np.nan)

## Desocupado
PNAD_COVID["Desocupado"] = PNAD_COVID["C015"].apply(lambda i: 1 if i == 1 else np.nan)

## Fora da Força de Trabalho
PNAD_COVID["Fora_FT"] = PNAD_COVID["C015"].apply(lambda i: 1 if i == 2 else np.nan)

In [6]:
## Vendo Ocupados e Desocupados por Mês (sem pesos)
ocupacao = pd.DataFrame(PNAD_COVID.groupby("V1013")[["Ocupado","Desocupado","Fora_FT", "V1032"]].count())
ocupacao["Taxa_Desocupacao"] = ocupacao["Desocupado"] / (ocupacao["Ocupado"] + ocupacao["Desocupado"])
ocupacao["Taxa_Participacao"] = (ocupacao["Ocupado"] + ocupacao["Desocupado"]) / ocupacao["V1032"]
ocupacao["Nivel_Ocupacao"] = ocupacao["Ocupado"] / ocupacao["V1032"]
ocupacao[["Taxa_Desocupacao", "Taxa_Participacao", "Nivel_Ocupacao"]]*100

       Taxa_Desocupacao  Taxa_Participacao  Nivel_Ocupacao
V1013
5              9.937047          43.338219       39.031680
6             11.366228          43.236552       38.322186
7             11.969057          42.230442       37.175856
8             12.472072          42.614095       37.299234
9             12.938650          43.168051       37.582688
10            13.020968          43.710393       38.018877
11            13.301538          44.086064       38.221939

### Desafio: como calcular com pesos?

Resultados do IBGE: https://agenciabrasil.ebc.com.br/economia/noticia/2020-12/pnad-covid-19-desemprego-chega-142-em-novembro

In [7]:
## Calculando variáveis com pesos por mês
ocupados_mes = PNAD_COVID.groupby(["V1013", "Ocupado"])["V1032"].sum()
desocupados_mes = PNAD_COVID.groupby(["V1013", "Desocupado"])["V1032"].sum()
populacao_mes = PNAD_COVID.query("A002 >= 14").groupby(["V1013", "Ano"])["V1032"].sum()

In [8]:
desocupados_mes / 1000000

V1013  Desocupado
5      1.0           10.129077
6      1.0           11.815274
7      1.0           12.253093
8      1.0           12.926400
9      1.0           13.486289
10     1.0           13.763069
11     1.0           14.038444
Name: V1032, dtype: float64

In [9]:
## Taxa de Desocupação
100 * desocupados_mes / (desocupados_mes + ocupados_mes)

V1013  Desocupado
5      1.0           10.714827
6      1.0           12.402611
7      1.0           13.071819
8      1.0           13.597067
9      1.0           13.986948
10     1.0           14.058701
11     1.0           14.223454
Name: V1032, dtype: float64

In [10]:
## Taxa de Participação
100 * (desocupados_mes + ocupados_mes) / populacao_mes

V1013  Desocupado
5      1.0           55.642742
6      1.0           55.989828
7      1.0           55.071697
8      1.0           55.819533
9      1.0           56.541493
10     1.0           57.383688
11     1.0           57.806241
Name: V1032, dtype: float64

In [11]:
## Nível de Ocupação
100 * ocupados_mes / populacao_mes

V1013  Ocupado
5      1.0        49.680718
6      1.0        49.045627
7      1.0        47.872824
8      1.0        48.229714
9      1.0        48.633064
10     1.0        49.316287
11     1.0        49.584198
Name: V1032, dtype: float64

## Criando o Painel

In [12]:
## Criando id do domicílio e do indivíduo
PNAD_COVID['iddom'] = PNAD_COVID["UPA"].astype(str) + PNAD_COVID["V1008"].astype(str)
PNAD_COVID['idind'] = PNAD_COVID['iddom'].astype(str) + PNAD_COVID['A001'].astype(str) + PNAD_COVID['A001B1'].astype(str) + PNAD_COVID['A001B2'].astype(str) + PNAD_COVID['A001B3'].astype(str)

In [13]:
## Ordenando o DataFrame
PNAD_COVID.sort_values(by=['idind', 'V1013'], inplace=True)

In [14]:
## Vendo o número de aparições e adicionando como coluna
PNAD_COVID["Aparições"] = PNAD_COVID.groupby('idind')['idind'].transform('count')
PNAD_COVID.head()

,Ano,UF,CAPITAL,RM_RIDE,V1008,V1012,V1013,V1016,UPA,V1022,...,C009A,A006A,A006B,A007A,Ocupado,Desocupado,Fora_FT,iddom,idind,Aparições
916,2020,11,11.0,NaN,10,4,5,1,110000016,1,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,11000001610,1100000161011861976,4
1003,2020,11,11.0,NaN,10,4,7,3,110000016,1,...,1.0,NaN,NaN,NaN,1.0,NaN,NaN,11000001610,1100000161011861976,4
997,2020,11,11.0,NaN,10,4,9,5,110000016,1,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,11000001610,1100000161011861976,4
1071,2020,11,11.0,NaN,10,4,10,6,110000016,1,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,11000001610,1100000161011861976,4
917,2020,11,11.0,NaN,10,4,5,1,110000016,1,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,11000001610,110000016102221981,4

In [15]:
## Vendo distribuição de aparições
PNAD_COVID["Aparições"].value_counts()

7    1452353
6     500646
5     269010
4     178812
3     121107
2      79488
1      49043
Name: Aparições, dtype: int64

In [16]:
## Pegando apenas as pessoas com pelo menos 5 entrevistas
PNAD_COVID = PNAD_COVID.query("Aparições >= 5")

In [17]:
## Vendo o novo tamanho da base
print(f"Linhas: {PNAD_COVID.shape[0]}; Colunas: {PNAD_COVID.shape[1]}")

Linhas: 2222009; Colunas: 94

In [18]:
## Montando o Painel
# Primeiro Nível: idind
# Segundo Nível: mês (V1013)

## Renomeando coluna de mês
PNAD_COVID.rename(columns={"V1013":"Mês"}, inplace=True)

In [19]:
## Montando a estrutura do painel
PNAD_COVID = PNAD_COVID.set_index(["idind", "Mês"], drop=False)

In [20]:
## Vendo o resultado
PNAD_COVID

                          Ano  UF  CAPITAL  RM_RIDE  V1008  V1012  Mês  V1016  \
idind               Mês
11000001611221974   5    2020  11     11.0      NaN      1      1    5      1
                    6    2020  11     11.0      NaN      1      1    6      2
                    7    2020  11     11.0      NaN      1      1    7      3
                    8    2020  11     11.0      NaN      1      1    8      4
                    9    2020  11     11.0      NaN      1      1    9      5
...                       ...  ..      ...      ...    ...    ...  ...    ...
5300510679419102001 7    2020  53     53.0      NaN      9      4    7      3
                    8    2020  53     53.0      NaN      9      4    8      4
                    9    2020  53     53.0      NaN      9      4    9      5
                    10   2020  53     53.0      NaN      9      4   10      6
                    11   2020  53     53.0      NaN      9      4   11      7

                               UPA  V1022  ...  C009A  A006A  A006B  A007A  \
idind               Mês                    ...
11000001611221974   5    110000016      1  ...    NaN    NaN    NaN    NaN
                    6    110000016      1  ...    NaN    NaN    NaN    NaN
                    7    110000016      1  ...    NaN    NaN    NaN    NaN
                    8    110000016      1  ...    NaN    NaN    NaN    NaN
                    9    110000016      1  ...    NaN    NaN    NaN    NaN
...                            ...    ...  ...    ...    ...    ...    ...
5300510679419102001 7    530051067      1  ...    NaN    NaN    NaN    NaN
                    8    530051067      1  ...    NaN    NaN    NaN    NaN
                    9    530051067      1  ...    NaN    NaN    NaN    NaN
                    10   530051067      1  ...    NaN    NaN    NaN    NaN
                    11   530051067      1  ...    NaN    1.0    4.0    NaN

                         Ocupado  Desocupado  Fora_FT       iddom  \
idind               Mês
11000001611221974   5        1.0         NaN      NaN  1100000161
                    6        1.0         NaN      NaN  1100000161
                    7        1.0         NaN      NaN  1100000161
                    8        1.0         NaN      NaN  1100000161
                    9        1.0         NaN      NaN  1100000161
...                          ...         ...      ...         ...
5300510679419102001 7        NaN         NaN      1.0  5300510679
                    8        NaN         NaN      1.0  5300510679
                    9        NaN         NaN      1.0  5300510679
                    10       NaN         NaN      1.0  5300510679
                    11       NaN         NaN      1.0  5300510679

                                       idind  Aparições
idind               Mês
11000001611221974   5      11000001611221974          7
                    6      11000001611221974          7
                    7      11000001611221974          7
                    8      11000001611221974          7
                    9      11000001611221974          7
...                                      ...        ...
5300510679419102001 7    5300510679419102001          7
                    8    5300510679419102001          7
                    9    5300510679419102001          7
                    10   5300510679419102001          7
                    11   5300510679419102001          7

[2222009 rows x 94 columns]

## Investigando renda e horas trabalhadas

In [21]:
# Recebeu auxílio emergencial?
PNAD_COVID["recebeu_auxilio"] = PNAD_COVID["D0051"].apply(lambda i: 1 if i == 1 else 0)

In [22]:
## Descrevendo horas normalmente trabalhadas (C008) e de fato trabalhadas na semana passada (C009)
PNAD_COVID.rename(columns={"C008":"horas_hab", "C009":"horas_efet"}, inplace=True)
PNAD_COVID[["horas_hab","horas_efet"]].describe()

# Média caiu, ao mesmo tempo que desvio-padrão aumentou

           horas_hab     horas_efet
count  857044.000000  857044.000000
mean       39.668323      32.736122
std        11.182892      17.023282
min         1.000000       0.000000
25%        40.000000      20.000000
50%        40.000000      40.000000
75%        44.000000      44.000000
max       120.000000     120.000000

In [23]:
## Descrevendo renda em dinheiro (C01012) ou em produtos (C01022)
PNAD_COVID[["C01012","C01022"]].describe()

              C01012        C01022
count  831604.000000   8799.000000
mean     2262.737915   1004.402546
std      2997.736463   1768.776372
min         2.000000      5.000000
25%      1045.000000    200.000000
50%      1500.000000    414.000000
75%      2500.000000   1045.000000
max    200000.000000  20000.000000

In [24]:
## Jeito errado (como descobrir que está errado?):
PNAD_COVID["Salário"] = PNAD_COVID["C01012"] + PNAD_COVID["C01022"]
PNAD_COVID["Salário"].describe()

count     3083.000000
mean      2324.099578
std       2386.539985
min         26.000000
25%       1194.000000
50%       1788.000000
75%       2600.000000
max      20060.000000
Name: Salário, dtype: float64

In [25]:
## Jeito certo:
PNAD_COVID["Salário"] = PNAD_COVID[["C01012","C01022"]].sum(axis=1, min_count=1)
PNAD_COVID[["Salário", "C01012","C01022"]].describe()

# Dois NaNs resultam em um NaN, um valor e outro NaN resulta no valor

             Salário         C01012        C01022
count  837320.000000  831604.000000   8799.000000
mean     2257.846031    2262.737915   1004.402546
std      2994.232891    2997.736463   1768.776372
min         2.000000       2.000000      5.000000
25%      1045.000000    1045.000000    200.000000
50%      1500.000000    1500.000000    414.000000
75%      2500.000000    2500.000000   1045.000000
max    200000.000000  200000.000000  20000.000000

In [26]:
## Contando números de pessoas que perderam o emprego durante a pandemia
# Criando uma coluna com a contagem de NaNs por grupo
# Usamos o transform para o resultado vir para uma coluna do próprio DataFrame (ao invés de uma série separada com apenas valores do grupo)
PNAD_COVID['quantidade_nas'] = PNAD_COVID.Salário.isnull().groupby('idind').transform('sum').astype(int)

In [27]:
## Vendo o DataFrame
PNAD_COVID['quantidade_nas']

idind                Mês
11000001611221974    5      0
                     6      0
                     7      0
                     8      0
                     9      0
                           ..
5300510679419102001  7      7
                     8      7
                     9      7
                     10     7
                     11     7
Name: quantidade_nas, Length: 2222009, dtype: int64

In [28]:
## Aplicando a função
# Além de perder o emprego, isso conta pessoas afastadas sem remuneração
# Alternativa: usar DataFrame.apply, mas demora cerca de 100x mais (não é brincadeira)
# Com apply: 2min30s; com np.where, 0.3s
PNAD_COVID['perdeu_ganhou_afastado_emprego'] = np.where(
    (PNAD_COVID.quantidade_nas > 0) & (PNAD_COVID.quantidade_nas < PNAD_COVID.Aparições),
    1,
    0
)

In [29]:
## Contando
PNAD_COVID['perdeu_ganhou_afastado_emprego'].value_counts(dropna=False, normalize=True)

0    0.858798
1    0.141202
Name: perdeu_ganhou_afastado_emprego, dtype: float64

In [30]:
## Vendo se a função funcionou
PNAD_COVID[["Ocupado","Salário","perdeu_ganhou_afastado_emprego","Aparições","quantidade_nas"]].query('perdeu_ganhou_afastado_emprego == 1').head(30)

                          Ocupado  Salário  perdeu_ganhou_afastado_emprego  \
idind                Mês
11000001691591967    5        1.0    200.0                               1
                     6        1.0    200.0                               1
                     7        1.0    800.0                               1
                     8        1.0      NaN                               1
                     9        1.0      NaN                               1
                     10       1.0      NaN                               1
                     11       1.0      NaN                               1
11000005210230121977 5        1.0   1300.0                               1
                     6        NaN      NaN                               1
                     8        NaN      NaN                               1
                     10       NaN      NaN                               1
                     11       NaN      NaN                               1
11000005211631988    6        NaN      NaN                               1
                     7        1.0   8000.0                               1
                     8        1.0    850.0                               1
                     9        1.0    850.0                               1
                     10       1.0    850.0                               1
110000108122481952   5        1.0   1750.0                               1
                     6        1.0   2000.0                               1
                     7        1.0   2000.0                               1
                     8        1.0   2000.0                               1
                     9        NaN      NaN                               1
                     10       NaN      NaN                               1
                     11       NaN      NaN                               1
110000108122641970   5        NaN      NaN                               1
                     6        NaN      NaN                               1
                     7        NaN      NaN                               1
                     8        NaN      NaN                               1
                     9        NaN      NaN                               1
                     10       1.0   1045.0                               1

                          Aparições  quantidade_nas
idind                Mês
11000001691591967    5            7               4
                     6            7               4
                     7            7               4
                     8            7               4
                     9            7               4
                     10           7               4
                     11           7               4
11000005210230121977 5            5               4
                     6            5               4
                     8            5               4
                     10           5               4
                     11           5               4
11000005211631988    6            5               1
                     7            5               1
                     8            5               1
                     9            5               1
                     10           5               1
110000108122481952   5            7               3
                     6            7               3
                     7            7               3
                     8            7               3
                     9            7               3
                     10           7               3
                     11           7               3
110000108122641970   5            7               5
                     6            7               5
                     7            7               5
                     8            7               5
                     9            7               5
                     10           7               5

In [31]:
## Restringindo a base apenas a quem esteve empregado em algum momento
PNAD_COVID_EMPREGADOS = PNAD_COVID.query('perdeu_ganhou_afastado_emprego == 1 or quantidade_nas == 0')

## Restringindo a análise a apenas a pessoas que perderam/ganharam/foram afastados do emprego
# PNAD_COVID = PNAD_COVID.query('perdeu_ganhou_afastado_emprego == 1')

## Tamanho total da base
print(f"EMPREGADOS\nLinhas: {PNAD_COVID_EMPREGADOS.shape[0]}; Colunas: {PNAD_COVID_EMPREGADOS.shape[1]}")
print(f"TOTAL\nLinhas: {PNAD_COVID.shape[0]}; Colunas: {PNAD_COVID.shape[1]}")

EMPREGADOS
Linhas: 994872; Colunas: 98
TOTAL
Linhas: 2222009; Colunas: 98

## Modelos de Painel

In [32]:
## Biblioteca usada
from linearmodels import PanelOLS, FirstDifferenceOLS, PooledOLS, RandomEffects

In [33]:
## Criando dummies de cor e gênero
# Feminino
PNAD_COVID['feminino'] = PNAD_COVID['A003'] - 1
PNAD_COVID_EMPREGADOS['feminino'] = PNAD_COVID_EMPREGADOS['A003'] - 1

# Cor
PNAD_COVID.rename(columns={"A004":"cor"}, inplace=True)
PNAD_COVID["cor"].replace([1,2,3,4,5,9], ['branca','preta','amarela','parda','indigena',np.nan], inplace=True)
PNAD_COVID = pd.concat([PNAD_COVID, pd.get_dummies(PNAD_COVID['cor'])], axis=1)

PNAD_COVID_EMPREGADOS.rename(columns={"A004":"cor"}, inplace=True)
PNAD_COVID_EMPREGADOS["cor"].replace([1,2,3,4,5,9], ['branca','preta','amarela','parda','indigena',np.nan], inplace=True)
PNAD_COVID_EMPREGADOS = pd.concat([PNAD_COVID_EMPREGADOS, pd.get_dummies(PNAD_COVID_EMPREGADOS['cor'])], axis=1)

/Users/vinicius/opt/anaconda3/envs/datascience/lib/python3.8/site-packages/pandas/core/frame.py:4441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(
/Users/vinicius/opt/anaconda3/envs/datascience/lib/python3.8/site-packages/pandas/core/series.py:4509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

In [34]:
## Contando valores
# Feminino
PNAD_COVID['feminino'].value_counts(dropna=False, normalize=True)

1    0.522053
0    0.477947
Name: feminino, dtype: float64

In [35]:
# Cor
PNAD_COVID['cor'].value_counts(dropna=False, normalize=True)

parda       0.479390
branca      0.429667
preta       0.080993
amarela     0.006157
indigena    0.003666
NaN         0.000126
Name: cor, dtype: float64

In [36]:
## Educação
## Remapeando
Valores_Educ = ["SI", "Fund Inc", "Fund Comp", "Méd Inc", "Med Comp", "Sup Inc", "Sup Comp", "Pós"]
PNAD_COVID["Educação"] = PNAD_COVID["A005"].replace([1, 2, 3, 4, 5, 6, 7, 8], Valores_Educ)
PNAD_COVID_EMPREGADOS["Educação"] = PNAD_COVID_EMPREGADOS["A005"].replace([1, 2, 3, 4, 5, 6, 7, 8], Valores_Educ)

Quando se usa regressões para calcular salários -- especialmente no contexto de diferenças raciais e de gênero --, o ideal é controlar para as horas trabalhadas, uma vez que, por exemplo, mulheres ofertam menos trabalho (em geral, se encarregam mais de trabalho doméstico).

Assim, recomenda-se (1) dividir a variável de rendimentos pelas horas trabalhadas ou (2) controlar horas como um regressor.

Para ter a interpretação em termos percentuais, usa-se log(salário)

In [37]:
# Log da renda por hora
PNAD_COVID["lsalariohora"] = np.log(PNAD_COVID["Salário"] / (PNAD_COVID["horas_hab"]*4))
PNAD_COVID_EMPREGADOS["lsalariohora"] = np.log(PNAD_COVID_EMPREGADOS["Salário"] / (PNAD_COVID_EMPREGADOS["horas_hab"]*4))

# Colocando Mês como dummies (e não valores contínuos)
PNAD_COVID["Mês"] = pd.Categorical(PNAD_COVID.Mês)
PNAD_COVID_EMPREGADOS["Mês"] = pd.Categorical(PNAD_COVID_EMPREGADOS.Mês)

In [38]:
# Imputando valores 0 nos salários nulos
PNAD_COVID["lsalariohora0"] = PNAD_COVID["lsalariohora"].fillna(value=0)
PNAD_COVID_EMPREGADOS["lsalariohora0"] = PNAD_COVID_EMPREGADOS["lsalariohora"].fillna(value=0)

In [39]:
## Definindo formula
# No linearmodels, precisamos incluir explicitamente um intercepto usando o 1+ (menos quando usarmos primeiras diferenças)
formula = "lsalariohora ~ 1 + Mês"

## Modelo
# Importante: DataFrame tem que estar no modelo MultiIndex indivíduo-tempo!
mod = PooledOLS.from_formula(formula=formula, data=PNAD_COVID)
mod = mod.fit(cov_type="robust")

## Sumário: note que não há o () ao final
print(mod.summary)

## Dummies de tempo: salário médio aumentou em julho frente a maio?
# Efeito-Composição: mais afetados pela crise foram os mais vulneráveis;
# como pessoas demitidas tem renda NaN, essas linhas são retiradas da análise, deixando apenas pessoas mais bem-remuneradas

# Mais detalhes: https://blogdoibre.fgv.br/posts/decomposicao-mostra-que-impacto-da-pandemia-influenciou-renda-media-positivamente

/Users/vinicius/opt/anaconda3/envs/datascience/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          PooledOLS Estimation Summary
================================================================================
Dep. Variable:           lsalariohora   R-squared:                     5.261e-05
Estimator:                  PooledOLS   R-squared (Between):             -0.0075
No. Observations:              837320   R-squared (Within):               0.0002
Date:                Fri, Oct 15 2021   R-squared (Overall):           5.261e-05
Time:                        17:30:24   Log-likelihood                -1.021e+06
Cov. Estimator:                Robust
                                        F-statistic:                      7.3421
Entities:                      153892   P-value                           0.0000
Avg Obs:                       5.4410   Distribution:                F(6,837313)
Min Obs:                       1.0000
Max Obs:                       7.0000   F-statistic (robust):             7.1451
                                        P-value                           0.0000
Time periods:                       7   Distribution:                F(6,837313)
Avg Obs:                    1.196e+05
Min Obs:                    1.084e+05
Max Obs:                    1.233e+05

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
Intercept      2.3108     0.0026     899.08     0.0000      2.3057      2.3158
Mês[T.6]      -0.0034     0.0035    -0.9501     0.3420     -0.0103      0.0036
Mês[T.7]       0.0094     0.0035     2.6821     0.0073      0.0025      0.0162
Mês[T.8]       0.0134     0.0035     3.8623     0.0001      0.0066      0.0202
Mês[T.9]       0.0098     0.0035     2.8323     0.0046      0.0030      0.0166
Mês[T.10]      0.0106     0.0035     3.0609     0.0022      0.0038      0.0173
Mês[T.11]      0.0124     0.0034     3.5996     0.0003      0.0056      0.0191
==============================================================================

In [40]:
## Imputando os 0s como proxy para coletar pessoas que perderam o emprego
formula = "lsalariohora0 ~ 1 + Mês"

## Modelo
# Importante: DataFrame tem que estar no modelo MultiIndex indivíduo-tempo!
mod = PooledOLS.from_formula(formula=formula, data=PNAD_COVID_EMPREGADOS)
mod = mod.fit(cov_type="robust")
print(mod.summary)

## Note que, ao considerar apenas pessoas que tinham emprego em algum momento (podendo tê-lo perdido, 
# o que é captado pelo 0 no lugar do NaN), houve perda de renda na pandemia frente a maio (junho a setembro)
# Não se pode usar a base toda em virtude de existirem pessoas nunca empregadas

                          PooledOLS Estimation Summary
================================================================================
Dep. Variable:          lsalariohora0   R-squared:                        0.0003
Estimator:                  PooledOLS   R-squared (Between):          -3.187e-05
No. Observations:              994872   R-squared (Within):               0.0011
Date:                Fri, Oct 15 2021   R-squared (Overall):              0.0003
Time:                        17:30:34   Log-likelihood                -1.535e+06
Cov. Estimator:                Robust
                                        F-statistic:                      48.238
Entities:                      344715   P-value                           0.0000
Avg Obs:                       2.8861   Distribution:                F(6,994865)
Min Obs:                       0.0000
Max Obs:                       7.0000   F-statistic (robust):             47.826
                                        P-value                           0.0000
Time periods:                       7   Distribution:                F(6,994865)
Avg Obs:                    1.421e+05
Min Obs:                    1.272e+05
Max Obs:                    1.471e+05

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
Intercept      1.9685     0.0032     619.77     0.0000      1.9623      1.9748
Mês[T.6]      -0.0115     0.0044    -2.6291     0.0086     -0.0201     -0.0029
Mês[T.7]      -0.0496     0.0044    -11.317     0.0000     -0.0582     -0.0410
Mês[T.8]      -0.0373     0.0044    -8.5432     0.0000     -0.0458     -0.0287
Mês[T.9]      -0.0238     0.0043    -5.4979     0.0000     -0.0324     -0.0153
Mês[T.10]     -0.0017     0.0043    -0.3992     0.6897     -0.0102      0.0068
Mês[T.11]      0.0058     0.0043     1.3315     0.1830     -0.0027      0.0142
==============================================================================

In [41]:
## Com pesos
pesos_empregados = PNAD_COVID_EMPREGADOS.V1032

mod = PooledOLS.from_formula(formula=formula, data=PNAD_COVID_EMPREGADOS, weights=pesos_empregados)
mod = mod.fit(cov_type="robust")
print(mod.summary)

                          PooledOLS Estimation Summary
================================================================================
Dep. Variable:          lsalariohora0   R-squared:                        0.0004
Estimator:                  PooledOLS   R-squared (Between):          -2.326e-06
No. Observations:              994872   R-squared (Within):               0.0014
Date:                Fri, Oct 15 2021   R-squared (Overall):              0.0004
Time:                        17:30:56   Log-likelihood                -1.531e+06
Cov. Estimator:                Robust
                                        F-statistic:                   9.081e+04
Entities:                      344715   P-value                           0.0000
Avg Obs:                       2.8861   Distribution:                F(6,994865)
Min Obs:                       0.0000
Max Obs:                       7.0000   F-statistic (robust):             31.824
                                        P-value                           0.0000
Time periods:                       7   Distribution:                F(6,994865)
Avg Obs:                    1.421e+05
Min Obs:                    1.272e+05
Max Obs:                    1.471e+05

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
Intercept      2.0192     0.0042     481.70     0.0000      2.0110      2.0274
Mês[T.6]      -0.0088     0.0058    -1.5246     0.1274     -0.0202      0.0025
Mês[T.7]      -0.0422     0.0058    -7.2215     0.0000     -0.0536     -0.0307
Mês[T.8]      -0.0226     0.0058    -3.8886     0.0001     -0.0341     -0.0112
Mês[T.9]      -0.0086     0.0058    -1.4764     0.1398     -0.0200      0.0028
Mês[T.10]      0.0167     0.0058     2.8904     0.0038      0.0054      0.0280
Mês[T.11]      0.0246     0.0058     4.2568     0.0000      0.0133      0.0359
==============================================================================

In [44]:
## Definindo formula
# No linearmodels, precisamos incluir explicitamente um intercepto usando o 1+ (menos quando usarmos primeiras diferenças)
formula = "lsalariohora0 ~ 1 + Mês + C(Educação, Treatment(reference='SI')) + feminino + C(cor, Treatment(reference='branca'))"

## Modelo
# Importante: DataFrame tem que estar no modelo MultiIndex indivíduo-tempo!
mod = PooledOLS.from_formula(formula=formula, data=PNAD_COVID_EMPREGADOS, weights=pesos_empregados)
mod = mod.fit(cov_type="robust")

In [46]:
## Sumário: note que não há o () ao final
# print(mod.summary)

In [47]:
## Discriminacao feminina teve alguma mudança ao longo do tempo?
# Interação entre variáveis!
formula = "lsalariohora0 ~ 1 + feminino*Mês + C(Educação, Treatment(reference='SI')) + C(cor, Treatment(reference='branca'))"

## Modelo
# Importante: DataFrame tem que estar no modelo MultiIndex indivíduo-tempo!
mod = PooledOLS.from_formula(formula=formula, data=PNAD_COVID_EMPREGADOS, weights=pesos_empregados)
mod = mod.fit(cov_type="robust")

In [48]:
## Sumário: note que não há o () ao final
print(mod.summary)

                          PooledOLS Estimation Summary
================================================================================
Dep. Variable:          lsalariohora0   R-squared:                        0.2170
Estimator:                  PooledOLS   R-squared (Between):              0.2935
No. Observations:              994872   R-squared (Within):              -0.0015
Date:                Fri, Oct 15 2021   R-squared (Overall):              0.2170
Time:                        17:33:53   Log-likelihood                -1.409e+06
Cov. Estimator:                Robust
                                        F-statistic:                   3.884e+04
Entities:                      344715   P-value                           0.0000
Avg Obs:                       2.8861   Distribution:               F(25,994846)
Min Obs:                       0.0000
Max Obs:                       7.0000   F-statistic (robust):             5471.7
                                        P-value                           0.0000
Time periods:                       7   Distribution:               F(25,994846)
Avg Obs:                    1.421e+05
Min Obs:                    1.272e+05
Max Obs:                    1.471e+05

                                                  Parameter Estimates
=======================================================================================================================
                                                     Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-----------------------------------------------------------------------------------------------------------------------
Intercept                                               1.3737     0.0109     125.67     0.0000      1.3522      1.3951
Mês[T.6]                                                0.0002     0.0068     0.0241     0.9808     -0.0132      0.0136
Mês[T.7]                                               -0.0149     0.0069    -2.1788     0.0293     -0.0284     -0.0015
Mês[T.8]                                                0.0102     0.0068     1.5030     0.1328     -0.0031      0.0235
Mês[T.9]                                                0.0249     0.0067     3.6989     0.0002      0.0117      0.0382
Mês[T.10]                                               0.0501     0.0067     7.4963     0.0000      0.0370      0.0632
Mês[T.11]                                               0.0574     0.0066     8.6276     0.0000      0.0443      0.0704
C(Educação, Treatment(reference='SI'))[T.Fund Comp]     0.6050     0.0108     56.069     0.0000      0.5838      0.6261
C(Educação, Treatment(reference='SI'))[T.Fund Inc]      0.3769     0.0101     37.426     0.0000      0.3571      0.3966
C(Educação, Treatment(reference='SI'))[T.Med Comp]      0.7554     0.0099     75.947     0.0000      0.7359      0.7749
C(Educação, Treatment(reference='SI'))[T.Méd Inc]       0.4486     0.0107     41.901     0.0000      0.4276      0.4696
C(Educação, Treatment(reference='SI'))[T.Pós]           2.1100     0.0117     180.83     0.0000      2.0871      2.1329
C(Educação, Treatment(reference='SI'))[T.Sup Comp]      1.5511     0.0104     149.53     0.0000      1.5307      1.5714
C(Educação, Treatment(reference='SI'))[T.Sup Inc]       0.8815     0.0109     80.694     0.0000      0.8601      0.9029
C(cor, Treatment(reference='branca'))[T.nan]           -0.4353     0.1126    -3.8664     0.0001     -0.6560     -0.2146
C(cor, Treatment(reference='branca'))[T.amarela]       -0.0421     0.0177    -2.3770     0.0175     -0.0767     -0.0074
C(cor, Treatment(reference='branca'))[T.indigena]      -0.2748     0.0220    -12.519     0.0000     -0.3178     -0.2318
C(cor, Treatment(reference='branca'))[T.parda]         -0.2207     0.0029    -77.325     0.0000     -0.2263     -0.2151
C(cor, Treatment(reference='branca'))[T.preta]         -0.1986     0.0046    -43.316     0.0000     -0.2076     -0.1896
feminino                                               -0.2467     0.0074    -33.157     0.0000     -0.2613     -0.2321
feminino:Mês[T.6]                                      -0.0136     0.0102    -1.3310     0.1832     -0.0337      0.0064
feminino:Mês[T.7]                                      -0.0584     0.0104    -5.6108     0.0000     -0.0788     -0.0380
feminino:Mês[T.8]                                      -0.0760     0.0103    -7.3615     0.0000     -0.0962     -0.0558
feminino:Mês[T.9]                                      -0.0820     0.0103    -7.9771     0.0000     -0.1022     -0.0619
feminino:Mês[T.10]                                     -0.0809     0.0102    -7.9106     0.0000     -0.1009     -0.0608
feminino:Mês[T.11]                                     -0.0843     0.0102    -8.2510     0.0000     -0.1043     -0.0643
=======================================================================================================================

### Testando econometric_functions

In [45]:
import econometric_functions as ef

In [50]:
## OLS agrupado com pesos
mod = ef.pooled_ols(PNAD_COVID_EMPREGADOS, formula, weights=pesos_empregados, cov="robust")

                          PooledOLS Estimation Summary
================================================================================
Dep. Variable:          lsalariohora0   R-squared:                        0.2170
Estimator:                  PooledOLS   R-squared (Between):              0.2935
No. Observations:              994872   R-squared (Within):              -0.0015
Date:                Fri, Oct 15 2021   R-squared (Overall):              0.2170
Time:                        17:35:43   Log-likelihood                -1.409e+06
Cov. Estimator:                Robust
                                        F-statistic:                   3.884e+04
Entities:                      344715   P-value                           0.0000
Avg Obs:                       2.8861   Distribution:               F(25,994846)
Min Obs:                       0.0000
Max Obs:                       7.0000   F-statistic (robust):             5471.7
                                        P-value                           0.0000
Time periods:                       7   Distribution:               F(25,994846)
Avg Obs:                    1.421e+05
Min Obs:                    1.272e+05
Max Obs:                    1.471e+05

                                                  Parameter Estimates
=======================================================================================================================
                                                     Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-----------------------------------------------------------------------------------------------------------------------
Intercept                                               1.3737     0.0109     125.67     0.0000      1.3522      1.3951
Mês[T.6]                                                0.0002     0.0068     0.0241     0.9808     -0.0132      0.0136
Mês[T.7]                                               -0.0149     0.0069    -2.1788     0.0293     -0.0284     -0.0015
Mês[T.8]                                                0.0102     0.0068     1.5030     0.1328     -0.0031      0.0235
Mês[T.9]                                                0.0249     0.0067     3.6989     0.0002      0.0117      0.0382
Mês[T.10]                                               0.0501     0.0067     7.4963     0.0000      0.0370      0.0632
Mês[T.11]                                               0.0574     0.0066     8.6276     0.0000      0.0443      0.0704
C(Educação, Treatment(reference='SI'))[T.Fund Comp]     0.6050     0.0108     56.069     0.0000      0.5838      0.6261
C(Educação, Treatment(reference='SI'))[T.Fund Inc]      0.3769     0.0101     37.426     0.0000      0.3571      0.3966
C(Educação, Treatment(reference='SI'))[T.Med Comp]      0.7554     0.0099     75.947     0.0000      0.7359      0.7749
C(Educação, Treatment(reference='SI'))[T.Méd Inc]       0.4486     0.0107     41.901     0.0000      0.4276      0.4696
C(Educação, Treatment(reference='SI'))[T.Pós]           2.1100     0.0117     180.83     0.0000      2.0871      2.1329
C(Educação, Treatment(reference='SI'))[T.Sup Comp]      1.5511     0.0104     149.53     0.0000      1.5307      1.5714
C(Educação, Treatment(reference='SI'))[T.Sup Inc]       0.8815     0.0109     80.694     0.0000      0.8601      0.9029
C(cor, Treatment(reference='branca'))[T.nan]           -0.4353     0.1126    -3.8664     0.0001     -0.6560     -0.2146
C(cor, Treatment(reference='branca'))[T.amarela]       -0.0421     0.0177    -2.3770     0.0175     -0.0767     -0.0074
C(cor, Treatment(reference='branca'))[T.indigena]      -0.2748     0.0220    -12.519     0.0000     -0.3178     -0.2318
C(cor, Treatment(reference='branca'))[T.parda]         -0.2207     0.0029    -77.325     0.0000     -0.2263     -0.2151
C(cor, Treatment(reference='branca'))[T.preta]         -0.1986     0.0046    -43.316     0.0000     -0.2076     -0.1896
feminino                                               -0.2467     0.0074    -33.157     0.0000     -0.2613     -0.2321
feminino:Mês[T.6]                                      -0.0136     0.0102    -1.3310     0.1832     -0.0337      0.0064
feminino:Mês[T.7]                                      -0.0584     0.0104    -5.6108     0.0000     -0.0788     -0.0380
feminino:Mês[T.8]                                      -0.0760     0.0103    -7.3615     0.0000     -0.0962     -0.0558
feminino:Mês[T.9]                                      -0.0820     0.0103    -7.9771     0.0000     -0.1022     -0.0619
feminino:Mês[T.10]                                     -0.0809     0.0102    -7.9106     0.0000     -0.1009     -0.0608
feminino:Mês[T.11]                                     -0.0843     0.0102    -8.2510     0.0000     -0.1043     -0.0643
=======================================================================================================================

In [54]:
## Efeitos Fixos sem pesos (50% mais rápido)
mod_fixed = ef.fixed_effects(PNAD_COVID_EMPREGADOS, formula, cov="robust")

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:          lsalariohora0   R-squared:                        0.0041
Estimator:                   PanelOLS   R-squared (Between):              0.1421
No. Observations:              994872   R-squared (Within):               0.0041
Date:                Fri, Oct 15 2021   R-squared (Overall):              0.1079
Time:                        17:41:56   Log-likelihood                -8.525e+05
Cov. Estimator:                Robust
                                        F-statistic:                      137.28
Entities:                      344715   P-value                           0.0000
Avg Obs:                       2.8861   Distribution:               F(25,840955)
Min Obs:                       0.0000
Max Obs:                       7.0000   F-statistic (robust):             86.564
                                        P-value                           0.0000
Time periods:                       7   Distribution:               F(25,840955)
Avg Obs:                    1.421e+05
Min Obs:                    1.272e+05
Max Obs:                    1.471e+05

                                                  Parameter Estimates
=======================================================================================================================
                                                     Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-----------------------------------------------------------------------------------------------------------------------
Intercept                                               1.8220     0.0438     41.639     0.0000      1.7362      1.9077
Mês[T.6]                                               -0.0047     0.0038    -1.2457     0.2129     -0.0121      0.0027
Mês[T.7]                                               -0.0243     0.0036    -6.7806     0.0000     -0.0313     -0.0173
Mês[T.8]                                               -0.0037     0.0035    -1.0579     0.2901     -0.0105      0.0031
Mês[T.9]                                                0.0112     0.0035     3.2467     0.0012      0.0045      0.0180
Mês[T.10]                                               0.0336     0.0035     9.4861     0.0000      0.0266      0.0405
Mês[T.11]                                               0.0389     0.0037     10.615     0.0000      0.0317      0.0461
C(Educação, Treatment(reference='SI'))[T.Fund Comp]     0.2085     0.0303     6.8798     0.0000      0.1491      0.2679
C(Educação, Treatment(reference='SI'))[T.Fund Inc]      0.1558     0.0272     5.7209     0.0000      0.1024      0.2092
C(Educação, Treatment(reference='SI'))[T.Med Comp]      0.2982     0.0312     9.5674     0.0000      0.2371      0.3592
C(Educação, Treatment(reference='SI'))[T.Méd Inc]       0.2592     0.0309     8.3967     0.0000      0.1987      0.3197
C(Educação, Treatment(reference='SI'))[T.Pós]           0.8154     0.0409     19.925     0.0000      0.7352      0.8957
C(Educação, Treatment(reference='SI'))[T.Sup Comp]      0.6949     0.0364     19.105     0.0000      0.6236      0.7662
C(Educação, Treatment(reference='SI'))[T.Sup Inc]       0.4497     0.0352     12.768     0.0000      0.3807      0.5187
C(cor, Treatment(reference='branca'))[T.nan]           -0.4698     0.1481    -3.1718     0.0015     -0.7602     -0.1795
C(cor, Treatment(reference='branca'))[T.amarela]       -0.0454     0.0406    -1.1187     0.2632     -0.1250      0.0342
C(cor, Treatment(reference='branca'))[T.indigena]      -0.0170     0.0603    -0.2810     0.7787     -0.1352      0.1013
C(cor, Treatment(reference='branca'))[T.parda]          0.0008     0.0128     0.0630     0.9497     -0.0244      0.0260
C(cor, Treatment(reference='branca'))[T.preta]          0.0052     0.0207     0.2538     0.7996     -0.0352      0.0457
feminino                                               -0.4800     0.0718    -6.6840     0.0000     -0.6208     -0.3393
feminino:Mês[T.6]                                      -0.0149     0.0060    -2.5014     0.0124     -0.0266     -0.0032
feminino:Mês[T.7]                                      -0.0611     0.0056    -10.833     0.0000     -0.0722     -0.0501
feminino:Mês[T.8]                                      -0.0785     0.0055    -14.370     0.0000     -0.0892     -0.0677
feminino:Mês[T.9]                                      -0.0808     0.0055    -14.814     0.0000     -0.0915     -0.0701
feminino:Mês[T.10]                                     -0.0800     0.0056    -14.278     0.0000     -0.0909     -0.0690
feminino:Mês[T.11]                                     -0.0802     0.0058    -13.890     0.0000     -0.0915     -0.0689
=======================================================================================================================

F-test for Poolability: 11.472
P-value: 0.0000
Distribution: F(153891,840955)

Included effects: Entity

In [51]:
## Efeitos fixos com pesos
mod_fixed = ef.fixed_effects(PNAD_COVID_EMPREGADOS, formula, weights=pesos_empregados, cov="robust")

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:          lsalariohora0   R-squared:                        0.0041
Estimator:                   PanelOLS   R-squared (Between):              0.1427
No. Observations:              994872   R-squared (Within):               0.0041
Date:                Fri, Oct 15 2021   R-squared (Overall):              0.1068
Time:                        17:37:08   Log-likelihood                -8.578e+05
Cov. Estimator:                Robust
                                        F-statistic:                   5.903e+04
Entities:                      344715   P-value                           0.0000
Avg Obs:                       2.8861   Distribution:               F(25,840955)
Min Obs:                       0.0000
Max Obs:                       7.0000   F-statistic (robust):             53.083
                                        P-value                           0.0000
Time periods:                       7   Distribution:               F(25,840955)
Avg Obs:                    1.421e+05
Min Obs:                    1.272e+05
Max Obs:                    1.471e+05

                                                  Parameter Estimates
=======================================================================================================================
                                                     Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-----------------------------------------------------------------------------------------------------------------------
Intercept                                               1.8279     0.0551     33.180     0.0000      1.7200      1.9359
Mês[T.6]                                               -0.0014     0.0050    -0.2909     0.7711     -0.0112      0.0083
Mês[T.7]                                               -0.0173     0.0047    -3.6585     0.0003     -0.0266     -0.0080
Mês[T.8]                                                0.0058     0.0046     1.2757     0.2020     -0.0031      0.0148
Mês[T.9]                                                0.0213     0.0046     4.6579     0.0000      0.0124      0.0303
Mês[T.10]                                               0.0493     0.0047     10.571     0.0000      0.0401      0.0584
Mês[T.11]                                               0.0555     0.0048     11.502     0.0000      0.0461      0.0650
C(Educação, Treatment(reference='SI'))[T.Fund Comp]     0.2692     0.0399     6.7396     0.0000      0.1909      0.3475
C(Educação, Treatment(reference='SI'))[T.Fund Inc]      0.1929     0.0358     5.3835     0.0000      0.1227      0.2631
C(Educação, Treatment(reference='SI'))[T.Med Comp]      0.3507     0.0413     8.4844     0.0000      0.2697      0.4317
C(Educação, Treatment(reference='SI'))[T.Méd Inc]       0.3059     0.0410     7.4618     0.0000      0.2256      0.3863
C(Educação, Treatment(reference='SI'))[T.Pós]           0.7968     0.0561     14.194     0.0000      0.6867      0.9068
C(Educação, Treatment(reference='SI'))[T.Sup Comp]      0.7188     0.0491     14.631     0.0000      0.6225      0.8151
C(Educação, Treatment(reference='SI'))[T.Sup Inc]       0.4858     0.0464     10.468     0.0000      0.3949      0.5768
C(cor, Treatment(reference='branca'))[T.nan]           -0.4464     0.1315    -3.3948     0.0007     -0.7041     -0.1887
C(cor, Treatment(reference='branca'))[T.amarela]       -0.0051     0.0495    -0.1036     0.9175     -0.1021      0.0918
C(cor, Treatment(reference='branca'))[T.indigena]       0.0230     0.0784     0.2934     0.7692     -0.1306      0.1766
C(cor, Treatment(reference='branca'))[T.parda]         -0.0126     0.0167    -0.7511     0.4526     -0.0453      0.0202
C(cor, Treatment(reference='branca'))[T.preta]         -0.0140     0.0268    -0.5204     0.6028     -0.0666      0.0386
feminino                                               -0.4809     0.0854    -5.6308     0.0000     -0.6484     -0.3135
feminino:Mês[T.6]                                      -0.0180     0.0078    -2.3205     0.0203     -0.0332     -0.0028
feminino:Mês[T.7]                                      -0.0660     0.0074    -8.9128     0.0000     -0.0805     -0.0515
feminino:Mês[T.8]                                      -0.0814     0.0071    -11.407     0.0000     -0.0954     -0.0674
feminino:Mês[T.9]                                      -0.0873     0.0072    -12.202     0.0000     -0.1013     -0.0733
feminino:Mês[T.10]                                     -0.0861     0.0073    -11.763     0.0000     -0.1004     -0.0717
feminino:Mês[T.11]                                     -0.0851     0.0076    -11.220     0.0000     -0.1000     -0.0702
=======================================================================================================================

F-test for Poolability: 11.096
P-value: 0.0000
Distribution: F(153891,840955)

Included effects: Entity

In [55]:
## Efeitos Aleatórios sem pesos
mod_random = ef.random_effects(PNAD_COVID_EMPREGADOS, formula, cov="robust")

                        RandomEffects Estimation Summary
================================================================================
Dep. Variable:          lsalariohora0   R-squared:                        0.0584
Estimator:              RandomEffects   R-squared (Between):              0.2831
No. Observations:              994872   R-squared (Within):               0.0004
Date:                Fri, Oct 15 2021   R-squared (Overall):              0.2119
Time:                        17:42:56   Log-likelihood                -9.381e+05
Cov. Estimator:                Robust
                                        F-statistic:                      2469.0
Entities:                      344715   P-value                           0.0000
Avg Obs:                       2.8861   Distribution:               F(25,994846)
Min Obs:                       0.0000
Max Obs:                       7.0000   F-statistic (robust):             2076.6
                                        P-value                           0.0000
Time periods:                       7   Distribution:               F(25,994846)
Avg Obs:                    1.421e+05
Min Obs:                    1.272e+05
Max Obs:                    1.471e+05

                                                  Parameter Estimates
=======================================================================================================================
                                                     Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-----------------------------------------------------------------------------------------------------------------------
Intercept                                               1.4414     0.0144     99.802     0.0000      1.4131      1.4697
Mês[T.6]                                               -0.0055     0.0036    -1.5440     0.1226     -0.0126      0.0015
Mês[T.7]                                               -0.0257     0.0035    -7.3902     0.0000     -0.0325     -0.0189
Mês[T.8]                                               -0.0053     0.0034    -1.5784     0.1145     -0.0120      0.0013
Mês[T.9]                                                0.0092     0.0034     2.7480     0.0060      0.0026      0.0158
Mês[T.10]                                               0.0314     0.0034     9.2455     0.0000      0.0247      0.0381
Mês[T.11]                                               0.0367     0.0035     10.590     0.0000      0.0299      0.0435
C(Educação, Treatment(reference='SI'))[T.Fund Comp]     0.4855     0.0153     31.675     0.0000      0.4554      0.5155
C(Educação, Treatment(reference='SI'))[T.Fund Inc]      0.2966     0.0141     20.964     0.0000      0.2689      0.3243
C(Educação, Treatment(reference='SI'))[T.Med Comp]      0.6615     0.0143     46.409     0.0000      0.6336      0.6895
C(Educação, Treatment(reference='SI'))[T.Méd Inc]       0.4290     0.0152     28.212     0.0000      0.3992      0.4588
C(Educação, Treatment(reference='SI'))[T.Pós]           1.8438     0.0164     112.73     0.0000      1.8117      1.8758
C(Educação, Treatment(reference='SI'))[T.Sup Comp]      1.4297     0.0149     96.131     0.0000      1.4005      1.4588
C(Educação, Treatment(reference='SI'))[T.Sup Inc]       0.8438     0.0157     53.779     0.0000      0.8131      0.8746
C(cor, Treatment(reference='branca'))[T.nan]           -0.5333     0.1321    -4.0383     0.0001     -0.7921     -0.2744
C(cor, Treatment(reference='branca'))[T.amarela]       -0.0923     0.0226    -4.0860     0.0000     -0.1365     -0.0480
C(cor, Treatment(reference='branca'))[T.indigena]      -0.2449     0.0326    -7.5081     0.0000     -0.3088     -0.1809
C(cor, Treatment(reference='branca'))[T.parda]         -0.2013     0.0043    -46.955     0.0000     -0.2097     -0.1929
C(cor, Treatment(reference='branca'))[T.preta]         -0.1948     0.0072    -26.924     0.0000     -0.2089     -0.1806
feminino                                               -0.2320     0.0063    -36.909     0.0000     -0.2443     -0.2197
feminino:Mês[T.6]                                      -0.0149     0.0056    -2.6827     0.0073     -0.0258     -0.0040
feminino:Mês[T.7]                                      -0.0605     0.0054    -11.214     0.0000     -0.0711     -0.0499
feminino:Mês[T.8]                                      -0.0783     0.0053    -14.892     0.0000     -0.0886     -0.0680
feminino:Mês[T.9]                                      -0.0809     0.0052    -15.459     0.0000     -0.0911     -0.0706
feminino:Mês[T.10]                                     -0.0803     0.0053    -15.131     0.0000     -0.0907     -0.0699
feminino:Mês[T.11]                                     -0.0810     0.0054    -14.978     0.0000     -0.0917     -0.0704
=======================================================================================================================

In [52]:
## Efeitos Aleatórios com pesos
mod_random = ef.random_effects(PNAD_COVID_EMPREGADOS, formula, weights=pesos_empregados, cov="robust")

                        RandomEffects Estimation Summary
================================================================================
Dep. Variable:          lsalariohora0   R-squared:                        0.4315
Estimator:              RandomEffects   R-squared (Between):              0.2916
No. Observations:              994872   R-squared (Within):              -0.0006
Date:                Fri, Oct 15 2021   R-squared (Overall):              0.2157
Time:                        17:38:34   Log-likelihood                -1.017e+06
Cov. Estimator:                Robust
                                        F-statistic:                   6.193e+04
Entities:                      344715   P-value                           0.0000
Avg Obs:                       2.8861   Distribution:               F(25,994846)
Min Obs:                       0.0000
Max Obs:                       7.0000   F-statistic (robust):             1059.9
                                        P-value                           0.0000
Time periods:                       7   Distribution:               F(25,994846)
Avg Obs:                    1.421e+05
Min Obs:                    1.272e+05
Max Obs:                    1.471e+05

                                                  Parameter Estimates
=======================================================================================================================
                                                     Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-----------------------------------------------------------------------------------------------------------------------
Intercept                                               1.4932     0.0216     69.081     0.0000      1.4509      1.5356
Mês[T.6]                                                0.0004     0.0053     0.0683     0.9455     -0.0100      0.0107
Mês[T.7]                                               -0.0154     0.0052    -2.9611     0.0031     -0.0257     -0.0052
Mês[T.8]                                                0.0083     0.0051     1.6265     0.1038     -0.0017      0.0183
Mês[T.9]                                                0.0237     0.0051     4.6542     0.0000      0.0137      0.0337
Mês[T.10]                                               0.0500     0.0051     9.8639     0.0000      0.0401      0.0599
Mês[T.11]                                               0.0560     0.0051     10.968     0.0000      0.0460      0.0660
C(Educação, Treatment(reference='SI'))[T.Fund Comp]     0.4824     0.0228     21.194     0.0000      0.4378      0.5270
C(Educação, Treatment(reference='SI'))[T.Fund Inc]      0.3100     0.0213     14.560     0.0000      0.2682      0.3517
C(Educação, Treatment(reference='SI'))[T.Med Comp]      0.6478     0.0213     30.363     0.0000      0.6060      0.6897
C(Educação, Treatment(reference='SI'))[T.Méd Inc]       0.3848     0.0226     17.033     0.0000      0.3406      0.4291
C(Educação, Treatment(reference='SI'))[T.Pós]           1.9716     0.0252     78.390     0.0000      1.9223      2.0209
C(Educação, Treatment(reference='SI'))[T.Sup Comp]      1.4354     0.0221     64.932     0.0000      1.3921      1.4788
C(Educação, Treatment(reference='SI'))[T.Sup Inc]       0.7782     0.0229     33.915     0.0000      0.7332      0.8232
C(cor, Treatment(reference='branca'))[T.nan]           -0.4744     0.1260    -3.7651     0.0002     -0.7213     -0.2274
C(cor, Treatment(reference='branca'))[T.amarela]       -0.0304     0.0299    -1.0194     0.3080     -0.0890      0.0281
C(cor, Treatment(reference='branca'))[T.indigena]      -0.2311     0.0382    -6.0460     0.0000     -0.3060     -0.1562
C(cor, Treatment(reference='branca'))[T.parda]         -0.2024     0.0061    -33.243     0.0000     -0.2143     -0.1904
C(cor, Treatment(reference='branca'))[T.preta]         -0.1916     0.0093    -20.681     0.0000     -0.2098     -0.1735
feminino                                               -0.2401     0.0084    -28.603     0.0000     -0.2565     -0.2236
feminino:Mês[T.6]                                      -0.0188     0.0080    -2.3518     0.0187     -0.0344     -0.0031
feminino:Mês[T.7]                                      -0.0676     0.0080    -8.4620     0.0000     -0.0833     -0.0520
feminino:Mês[T.8]                                      -0.0837     0.0078    -10.693     0.0000     -0.0990     -0.0684
feminino:Mês[T.9]                                      -0.0899     0.0078    -11.504     0.0000     -0.1052     -0.0746
feminino:Mês[T.10]                                     -0.0886     0.0078    -11.298     0.0000     -0.1039     -0.0732
feminino:Mês[T.11]                                     -0.0894     0.0079    -11.251     0.0000     -0.1049     -0.0738
=======================================================================================================================

In [53]:
## Teste de Hausman para ver qual modelo é preferido (com pesos)
ef.hausman_fe_re(PNAD_COVID_EMPREGADOS, formula, weights=pesos_empregados, cov="robust")

The value of H is 932.302387 with 25 degrees of freedom in the chi-squared distribution.
The p-value of the test is 0.0 and, therefore, H0 is REJECTED and fixed effects is preferred